name: igmr (x64-linux)
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install vcpkg
      run: |
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
    - name: Install vcpkg dependencies
      run: |
        cd vcpkg
        ./vcpkg install asio fmt libgit2 nlohmann-json spdlog sqlite3
    - name: 7-Zip binaries
      run: |
        cd vcpkg
        7z a igmr_x64-linux.7z installed scripts .vcpkg-root
    - name: Upload binaries to GitHub
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/kevinlul/edopro-vcpkg-cache/releases/22193553/assets{?name,label}
        asset_path: ./vcpkg/igmr_x64-linux.7z
        asset_name: igmr_x64-linux.7z
        asset_content_type: application/x-7z-compressed
