name: osx
on: push
jobs:
  build:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.11
      SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install 10.11 SDK
      run: |
        curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
          https://raw.githubusercontent.com/edo9300/ygopro/master/travis/get-osx-sdk.sh
        chmod +x get-osx-sdk.sh
        ./get-osx-sdk.sh $MACOSX_DEPLOYMENT_TARGET
    - name: Install 7-Zip and GNU Patch
      run: |
        brew update
        brew install p7zip gpatch
    - name: Build patched Irrlicht
      run: |
        curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
          https://raw.githubusercontent.com/edo9300/ygopro/master/irrlicht/irrlicht-macOS.patch
        curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
          https://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip
        7z x irrlicht-1.8.4.zip
        cd irrlicht-1.8.4
        /usr/local/opt/gpatch/bin/patch -p0 --binary -i ../irrlicht-macOS.patch
        xcodebuild -project source/Irrlicht/MacOSX/MacOSX.xcodeproj -configuration Release -target libIrrlicht.a SYMROOT=build -sdk $SDKROOT -parallelizeTargets
        mkdir -p ../irrlicht/lib
        cp -r include ../irrlicht/include
        cp source/Irrlicht/MacOSX/build/Release/libIrrlicht.a ../irrlicht/lib
    - name: Build libevent for pre-10.13 binary compatibility
      run: |
        curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
          https://github.com/libevent/libevent/releases/download/release-2.1.11-stable/libevent-2.1.11-stable.tar.gz
        tar xf libevent-2.1.11-stable.tar.gz
        cd libevent-2.1.11-stable
        ./configure --prefix ../libevent
        make -j2
        make install
    - name: Build Discord RPC with Payloads (edo9300/discord-rpc)
      run: |
        git clone --depth=1 https://github.com/edo9300/discord-rpc.git discord-rpc-payload
        mkdir -p discord-rpc-payload/build
        cd discord-rpc-payload/build
        cmake ..
        cmake --build . --target discord-rpc
        cmake --install . --prefix ../../discord-rpc
    - name: 7-Zip binaries
      run: 7z a dependencies_osx.7z irrlicht libevent discord-rpc
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: latest
        draft: false
        prerelease: true
    - name: Upload binaries to GitHub
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dependencies_osx.7z
        asset_name: dependencies_osx.7z
        asset_content_type: application/x-7z-compressed