name: vcpkg (x64-linux)
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install vcpkg
      run: |
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
    - name: Install dependencies
      run: |
        cp -r ports/discord-rpc-payload vcpkg/ports/discord-rpc-payload
        cd vcpkg
        ./vcpkg install \
          libevent sqlite3 \
          curl libgit2 fmt nlohmann-json \
          sdl2-mixer[libflac,mpg123,libvorbis] \
          discord-rpc-payload
    - name: 7-Zip binaries
      run: |
        cd vcpkg
        7z a installed_x64-linux.7z installed
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: latest
        draft: false
        prerelease: true
    - name: Upload binaries to GitHub
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vcpkg/installed_x64-linux.7z
        asset_name: installed_x64-linux.7z
        asset_content_type: application/x-7z-compressed
