name: vcpkg (x64-osx)
on: push
jobs:
  build:
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.11
      SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install 10.11 SDK
        run: |
          curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
            https://raw.githubusercontent.com/edo9300/ygopro/master/travis/get-osx-sdk.sh
          chmod +x get-osx-sdk.sh
          ./get-osx-sdk.sh $MACOSX_DEPLOYMENT_TARGET
      - name: Install Homebrew prerequisites
        run: |
          brew update
          brew install dos2unix p7zip gpatch yasm
      - name: Build patched Irrlicht
        run: |
          curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
            https://raw.githubusercontent.com/edo9300/ygopro/master/irrlicht/irrlicht-macOS.patch
          unix2dos irrlicht-macOS.patch
          curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name \
            https://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip
          7z x irrlicht-1.8.4.zip
          cd irrlicht-1.8.4
          /usr/local/opt/gpatch/bin/patch -p0 --binary -i ../irrlicht-macOS.patch
          xcodebuild -project source/Irrlicht/MacOSX/MacOSX.xcodeproj -configuration Release -target libIrrlicht.a SYMROOT=build -sdk $SDKROOT -parallelizeTargets
          mkdir -p ../irrlicht/lib
          cp -r include ../irrlicht/include
          cp source/Irrlicht/MacOSX/build/Release/libIrrlicht.a ../irrlicht/lib
      - name: Install vcpkg
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15
          SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
        run: |
          git clone --depth=1 https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
      - name: Install SDL2 from vcpkg
        env:
          SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
        run: |
          cd vcpkg
          ./vcpkg install sdl2
      - name: Install vcpkg dependencies
        run: |
          cp -r ports/discord-rpc-payload vcpkg/ports/discord-rpc-payload
          cp -r ports/sdl2-mixer-fixdynamic vcpkg/ports/sdl2-mixer-fixdynamic
          cd vcpkg
          ./vcpkg install \
            libevent[thread] \
            sdl2-mixer-fixdynamic[libflac,mpg123,libvorbis] \
            discord-rpc-payload
      - name: 7-Zip binaries
        run: |
          mv irrlicht vcpkg
          cd vcpkg
          7z a installed_x64-osx.7z installed scripts .vcpkg-root irrlicht
      - name: Upload binaries to GitHub
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/kevinlul/edopro-vcpkg-cache/releases/22193553/assets{?name,label}
          asset_path: ./vcpkg/installed_x64-osx.7z
          asset_name: installed_x64-osx.7z
          asset_content_type: application/x-7z-compressed
