name: vcpkg (x86-windows-static)
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install vcpkg
      shell: powershell
      run: |
        git clone --depth=1 https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
    - name: Install dependencies
      shell: bash
      run: |
        cp -r ports/discord-rpc-payload vcpkg/ports/discord-rpc-payload
        cd vcpkg
        ./vcpkg install --triplet x86-windows-static \
          lua[cpp] \
          libevent[thread] sqlite3 \
          bzip2 libjpeg-turbo libpng zlib \
          curl libgit2 fmt nlohmann-json \
          sdl2-mixer[libflac,mpg123,libvorbis] \
          discord-rpc-payload
    - name: Zip binaries
      shell: powershell
      run: |
        cd vcpkg
        Compress-Archive -Path installed -DestinationPath installed_x86-windows-static.zip
    - name: Upload binaries to GitHub
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/kevinlul/edopro-vcpkg-cache/releases/22193553/assets{?name,label}
        asset_path: ./vcpkg/installed_x86-windows-static.zip
        asset_name: installed_x86-windows-static.zip
        asset_content_type: application/zip
